[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[environments.production]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "INFO" }

[environments.development]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "DEBUG" } 