[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

# Let Railway handle startup automatically - remove custom startCommand
# Railway will use the Dockerfile CMD by default

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "INFO" }

[environments.development]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "DEBUG" } 