[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 30
healthcheckStartPeriod = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { 
    PYTHONPATH = "/app", 
    LOG_LEVEL = "INFO",
    PYTHONUNBUFFERED = "1"
}

[environments.development]
variables = { 
    PYTHONPATH = "/app", 
    LOG_LEVEL = "DEBUG",
    PYTHONUNBUFFERED = "1"
} 