[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

# Alternative startup command that can be used if shell script fails
# Uncomment the line below and comment out the CMD in Dockerfile if needed
# Multiple startup options - uncomment the one you want to use
startCommand = "python start_direct.py"
# startCommand = "python start.py"
# startCommand = "python start_simple.py"
# startCommand = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --workers 1"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "INFO" }

[environments.development]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "DEBUG" } 