[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

# Use Railway-specific startup script with enhanced PORT handling
startCommand = "python start_railway.py"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "INFO" }

[environments.development]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "DEBUG" } 