[build]
builder = "DOCKERFILE"

# Fallback start command
startCommand = "python start_railway.py"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 300
healthcheckStartPeriod = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "INFO" }

[environments.development]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "DEBUG" } 