[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckStartPeriod = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "INFO" }

[environments.development]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "DEBUG" } 