[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

# Alternative startup command that can be used if shell script fails
# Uncomment the line below and comment out the CMD in Dockerfile if needed
# startCommand = "python start.py"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "INFO" }

[environments.development]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "DEBUG" } 