[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 180
healthcheckStartPeriod = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[environments.production]
variables = { 
    PYTHONPATH = "/app", 
    LOG_LEVEL = "INFO",
    PYTHONUNBUFFERED = "1"
}

[environments.development]
variables = { 
    PYTHONPATH = "/app", 
    LOG_LEVEL = "DEBUG",
    PYTHONUNBUFFERED = "1"
} 