[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/ping"
healthcheckTimeout = 120
healthcheckStartPeriod = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "INFO" }

[environments.development]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "DEBUG" } 