[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

# Use shell script with explicit PORT environment variable handling
startCommand = "bash start_railway.sh"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

[environments.production]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "INFO" }

[environments.development]
variables = { PYTHONPATH = "/app", LOG_LEVEL = "DEBUG" } 