firecrawl:
  api_key: ${FIRECRAWL_API_KEY}
  base_url: https://api.firecrawl.dev
sites:
  judiciary_uk:
    check_interval_minutes: 1440
    detection_methods:
    - sitemap
    - firecrawl
    is_active: true
    name: Judiciary UK
    sitemap_url: https://www.judiciary.uk/sitemap.xml
    url: https://www.judiciary.uk/
  waverley_gov:
    check_interval_minutes: 1440
    detection_methods:
    - sitemap
    - firecrawl
    is_active: true
    name: Waverley Borough Council
    sitemap_url: https://www.waverley.gov.uk/sitemap.xml
    url: https://www.waverley.gov.uk/
system:
  log_level: INFO
  max_retries: 3
  output_directory: output
  timeout_seconds: 30
