# ==============================================================================
# Proxy Configuration for Aggregator
# ==============================================================================

# Enable proxy usage globally
proxy_enabled: true  # Now enabled with proper Tor control configuration

# Proxy provider selection
proxy_provider: "tor"

# Tor configuration (local Tor Browser)
proxy_host: "127.0.0.1"
proxy_port: 9050

# Session management
proxy_session_duration: 600  # 10 minutes
proxy_max_requests_per_session: 100
proxy_retry_attempts: 3
proxy_timeout: 30

# Adaptive settings
proxy_threshold: 50  # Use proxy for sites with >50 URLs
proxy_health_check: true

# ==============================================================================
# Provider-Specific Examples (for reference)
# ==============================================================================

# Bright Data Configuration
bright_data:
  host: "brd.superproxy.io"
  port: 22225
  format: "http://{username}-country-{country}-session-{session_id}:{password}@{host}:{port}"

# Oxylabs Configuration  
oxylabs:
  host: "pr.oxylabs.io"
  port: 7777
  format: "http://{username}-country-{country}-session-{session_id}:{password}@{host}:{port}"

# ProxyMesh Configuration
proxymesh:
  host: "proxy.proxymesh.com"
  port: 31280
  format: "http://{username}:{password}@{host}:{port}"

# Storm Proxies Configuration
storm_proxies:
  host: "residential.stormproxies.com"
  port: 10000
  format: "http://{username}:{password}@{host}:{port}"

# Tor Configuration (requires Tor to be running locally)
tor:
  host: "127.0.0.1"
  port: 9050  # SOCKS5 port
  control_port: 9051  # Control port for identity renewal
  control_password: "my_control_password_123"  # Set in torrc
  format: "socks5://{host}:{port}"
  max_circuits: 10  # Number of requests before renewing identity
  circuit_timeout: 300  # Circuit timeout in seconds 