# ==============================================================================
# sites_railway.yaml — Railway-Optimized Configuration
# ==============================================================================
# Purpose: Lightweight configuration for Railway deployment
# ==============================================================================

sites:
  waverley_gov:
    name: 'Waverley Borough Council'
    url: 'https://www.waverley.gov.uk/'
    sitemap_url: 'https://www.waverley.gov.uk/sitemap.xml'
    detection_methods: ['sitemap']  # Use only sitemap for Railway (lighter)
    check_interval_minutes: 1440
    is_active: true
    # Disable heavy operations for Railway
    enable_content_detection: false
    max_content_pages: 5  # Reduced for Railway
    content_timeout: 5  # Shorter timeout

  judiciary_uk:
    name: 'Judiciary UK'
    url: 'https://www.judiciary.uk/'
    sitemap_url: 'https://www.judiciary.uk/sitemap_index.xml'
    detection_methods: ['hybrid']  # Use hybrid detection for comprehensive monitoring
    check_interval_minutes: 1440
    is_active: true
    # Content detection settings
    enable_content_detection: true
    content_check_interval: 24  # Check content every 24 hours
    max_content_pages: 20  # Check content of top 20 pages
    content_timeout: 10  # 10 second timeout per page
    content_selectors: ['main', 'article', '.content', '#content', '.main-content']
    exclude_selectors: ['nav', 'footer', '.sidebar', '.ads', '.comments', '.header', '.menu']

firecrawl:
  api_key: ${FIRECRAWL_API_KEY}  # Use environment variable
  base_url: 'https://api.firecrawl.dev'

system:
  output_directory: 'output'
  log_level: 'INFO'
  max_retries: 2  # Reduced for Railway
  timeout_seconds: 15  # Shorter timeout for Railway 