# ==============================================================================
# sites.yaml.example — Example Configuration for Change Detection System
# ==============================================================================
# Purpose: Example configuration file showing the structure for site monitoring
# Copy this file to sites.yaml and update with your actual values
# ==============================================================================

sites:
  judiciary_uk:
    name: 'Judiciary UK'
    url: 'https://www.judiciary.uk/'
    sitemap_url: 'https://www.judiciary.uk/sitemap_index.xml'
    detection_methods: ['hybrid']  # Use hybrid detection for comprehensive monitoring
    check_interval_minutes: 1440
    is_active: true
    # Content detection settings
    enable_content_detection: true
    content_check_interval: 24  # Check content every 24 hours
    max_content_pages: 20  # Check content of top 20 pages
    content_timeout: 10  # 10 second timeout per page
    content_selectors: ['main', 'article', '.content', '#content', '.main-content']
    exclude_selectors: ['nav', 'footer', '.sidebar', '.ads', '.comments', '.header', '.menu']
  
  waverley_gov:
    name: 'Waverley Borough Council'
    url: 'https://www.waverley.gov.uk/'
    sitemap_url: 'https://www.waverley.gov.uk/sitemap.xml'
    detection_methods: ['hybrid']  # Use hybrid detection for comprehensive monitoring
    check_interval_minutes: 1440
    is_active: true
    # Content detection settings
    enable_content_detection: true
    content_check_interval: 24  # Check content every 24 hours
    max_content_pages: 15  # Check content of top 15 pages
    content_timeout: 10  # 10 second timeout per page
    content_selectors: ['main', 'article', '.content', '#content', '.main-content']
    exclude_selectors: ['nav', 'footer', '.sidebar', '.ads', '.comments', '.header', '.menu']

firecrawl:
  api_key: '${FIRECRAWL_API_KEY}'  # Set this environment variable or replace with your actual API key
  base_url: 'https://api.firecrawl.dev'
  # Performance optimization settings
  limit: 10  # Page limit (correct parameter name)
  wait_for: 100  # Reduced wait time (ms)
  timeout: 15000  # 15 second timeout per page
  max_age: 3600000  # 1 hour cache for 500% speed boost
  cache_duration_hours: 24
  adaptive_timeout: true
  max_retries: 3
  backoff_factor: 2.0
  parallel_processing: true
  incremental_crawl: true

system:
  output_directory: 'output'
  log_level: 'INFO'
  max_retries: 3
  timeout_seconds: 30 